[package]
name = "day7-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common/" }
regex = "1.7.0"
lazy_static = "1.4.0"
